[package]
name = "scrap-linux-udp"
version = "0.1.0"
edition = "2021"

[dependencies]
scrap-core-lite = { path = "../scrap-core-lite" }
scrap-edge = { path = "../scrap-edge" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
